# MyBatis 相关配置
mybatis:
  # 配置 Mybatis 日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
  # 指定 Mybatis 的 Mapper 文件位置
  mapper-locations: classpath:demos/web/mapper/*.xml
  # 指定 Mybatis 的实体目录
  type-aliases-package: com.example.assessment.mybatis.entity

# 应用服务 WEB 访问端口
server:
  port: 8081

# Spring 数据源相关配置
spring:
  profiles:
    active:
      - local
  datasource:
    # 数据库连接 URL
    url: jdbc:mysql://localhost:3306/assessment?useUnicode=true&characterEncoding=utf-8
    # 数据库用户名
    username: root
    # 数据库密码
    password: root
    # 数据库驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver


web:
  alioss:
    access-key-id: ${web.alioss.access-key-secret}
    access-key-secret: ${web.alioss.access-key-secret}
    bucket-name: ${web.alioss.bucket-name}
    endpoint: ${web.alioss.endpoint}